### ISSUE TITLE
1. Two Sum 两数之和

### ISSUE THREAD

**Issue by JamCh01** [blackfamilyleetcode/Leetcode#4]
Given an array of integers, return indices of the two numbers such that they add up to a specific target. You may assume that each input would have exactly one solution, and you may not use the same element twice.

Example:
```
Given nums = [2, 7, 11, 15], target = 9,

Because nums[0] + nums[1] = 2 + 7 = 9,
return [0, 1].
```

给定一个整数数组 nums 和一个目标值 target，请你在该数组中找出和为目标值的那 两个 整数，并返回他们的数组下标。

你可以假设每种输入只会对应一个答案。但是，你不能重复利用这个数组中同样的元素。

示例:
```
给定 nums = [2, 7, 11, 15], target = 9

因为 nums[0] + nums[1] = 2 + 7 = 9
所以返回 [0, 1]
```

Via [LeetCode](https://leetcode.com/problems/two-sum/) [力扣](https://leetcode-cn.com/problems/two-sum/)

**Comment by JamCh01** [comment]
```python
class Solution:
    def twoSum(self, nums: List[int], target: int) -> List[int]:
        if len(nums) <= 1:
            return False
        _ = {}
        for i in range(len(nums)):
            if nums[i] in _:
                return [_[nums[i]], i]
            else:
                _[target - nums[i]] = i

```
Runtime: 32 ms, faster than 97.27% of Python3 online submissions for Two Sum.
Memory Usage: 14.7 MB, less than 15.45% of Python3 online submissions for Two Sum.

**Comment by RomanHc** [comment]
var twoSum = function(nums, target) {
    let map = {};
    for (let i = 0; i < nums.length; ++i) {
        if (map[target - nums[i]] !== undefined) {
            return [map[target - nums[i]], i];
        }
        map[nums[i]] = i;
        
    }
};
执行用时 :80 ms, 在所有 JavaScript 提交中击败了95.52%的用户
内存消耗 :34.6 MB, 在所有 JavaScript 提交中击败了59.40%的用户

**Comment by RomanHc** [comment]
```javascript
function twoSum (nums, target) {
    let map = {};
    for (let i = 0; i < nums.length; ++i) {
        if (map[target - nums[i]] !== undefined) {
            return [map[target - nums[i]], i];
        }
        map[nums[i]] = i;
    }
};

```
执行用时 :80 ms, 在所有 JavaScript 提交中击败了95.52%的用户
内存消耗 :34.6 MB, 在所有 JavaScript 提交中击败了59.40%的用户

**Comment by knife0217** [comment]
```javascript
var twoSum = function(nums, target) {
        let map = new Map();
        let arr = [];
        for(let i in nums){
            map.set( nums[i], i) //设置值和下标为键值对
        }
        for(let j = 0; j < nums.length - 1; j++){
            if(map.has( target - nums[j] ) && map.get( target - nums[j]) != j ){  // .has 返回true或flase   .get 返回值（键值对中的下标）
                arr.push( j , map.get( target - nums[j] ) );
                return arr
            }
        }
    };
```
执行用时 :80 ms, 在所有 JavaScript 提交中击败了95.52%的用户
内存消耗 :37.4 MB, 在所有 JavaScript 提交中击败了5.01%的用户

学习了某大佬的Map方法的应用

**Comment by wentianyang** [comment]
`    public int[] twoSum(int[] nums, int target) {
        Map<Integer, Integer> map = new HashMap();
        int[] result = new int[2];
        for(int i = 0; i < nums.length; i++){
            if(map.containsKey(nums[i])){
                result[0] = map.get(nums[i]);
                result[1] = i;
                return result;
            }
            map.put(target - nums[i], i);
        }
        return result;
    }`
Runtime: 2 ms, faster than 98.87% of Java online submissions for Two Sum.
Memory Usage: 37.8 MB, less than 99.32% of Java online submissions for Two Sum.

**Comment by wentianyang** [comment]
```java
    public int[] twoSum(int[] nums, int target) {
        Map<Integer, Integer> map = new HashMap();
        int[] result = new int[2];
        for(int i = 0; i < nums.length; i++){
            if(map.containsKey(nums[i])){
                result[0] = map.get(nums[i]);
                result[1] = i;
                return result;
            }
            map.put(target - nums[i], i);
        }
        return result;
    }
```
Runtime: 2 ms, faster than 98.87% of Java online submissions for Two Sum.
Memory Usage: 37.8 MB, less than 99.32% of Java online submissions for Two Sum.

**Comment by zst96226** [comment]
```C#
public class Solution {
    public int[] TwoSum(int[] nums, int target) {
        
           
            int[] result = new int[2];
            Dictionary<int,int> dic=new Dictionary<int,int>();
            for (int i = 0; i < nums.Length; i++)
            {
               if (dic.ContainsKey(target - nums[i]))
                {
                    result[0] = dic[target - nums[i]];
                    result[1] = i;
                    return result;
                }
                if (dic.ContainsKey(nums[i]))
                { dic[nums[i]] = i; }
                else
                { dic.Add(nums[i], i); }
            }
            return result;
    }
}
```
Runtime: 260 ms, faster than 78.83% of C# online submissions for Two Sum.
Memory Usage: 29.4 MB, less than 16.43% of C# online submissions for Two Sum.

**Comment by zst96226** [comment]
> ```java
>     public  int [] twoSum（int [] nums，int target）{
>          Map < Integer，Integer > map =  new  HashMap（）;
>         int [] result =  new  int [ 2 ];
>         对于（诠释我=  0 ;我< NUMS 。长度;我++）{
>              如果（地图。的containsKey（NUMS [I]））{
>                 结果[ 0 ] =地图。得到（NUMS [I]）;
>                 结果[ 1 ] = i;
>                 返回结果;
>             }
>             地图。put（target - nums [i]，i）;
>         }
>         返回结果;
>     }
> ```
> 
> 运行时间：2毫秒，比两次总和的Java在线提交快98.87％。
> 内存使用量：37.8 MB，低于Java在线提交的两笔总和的99.32％。

2ms牛逼
